/**
 * Document Type Definitions with Governance Rules
 *
 * CRITICAL: These rules determine which documents can be synced to Alemba
 * and which are sensitive (requiring special handling)
 *
 * IMPORTANT RULES:
 * - Passport and Driving Licence MUST NEVER be synced to Alemba
 * - Sensitive documents are stored in a separate SharePoint library
 * - Sensitive documents are auto-deleted after supplier setup completion
 */

export const DOCUMENT_TYPES = {
  // Section 2 Documents
  LETTERHEAD_BANK_DETAILS: {
    id: 'letterhead_bank_details',
    name: 'Letterhead with Bank Details',
    description: 'Company letterhead containing bank account details',
    allowAlembaSync: true,
    isSensitive: false,
    required: true,
    section: 2,
    acceptedFormats: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 10
  },

  PROCUREMENT_APPROVAL: {
    id: 'procurement_approval',
    name: 'Procurement Approval Document',
    description: 'PBP approval certificate or procurement engagement evidence',
    allowAlembaSync: true,
    isSensitive: false,
    required: false, // Required only if procurement engaged = yes
    section: 2,
    conditionalRequired: {
      field: 'procurementEngaged',
      value: 'yes'
    },
    acceptedFormats: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 10
  },

  // Section 3 Documents (Sole Trader/Individual)
  CEST_FORM: {
    id: 'cest_form',
    name: 'CEST Assessment Form',
    description: 'HMRC Check Employment Status for Tax assessment',
    allowAlembaSync: true,
    isSensitive: false,
    required: false, // Required only for sole traders
    section: 3,
    conditionalRequired: {
      field: 'supplierType',
      value: 'sole_trader'
    },
    acceptedFormats: ['.pdf'],
    maxSizeMB: 5
  },

  PASSPORT: {
    id: 'passport',
    name: 'Passport',
    description: 'Valid passport for identity verification (sole traders only)',
    allowAlembaSync: false, // CRITICAL: NEVER sync to Alemba
    isSensitive: true,
    required: false, // Required for sole traders as ID
    section: 3,
    autoDeleteOnCompletion: true,
    retentionPeriod: '30 days after completion',
    acceptedFormats: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 5,
    warningMessage: 'This document contains sensitive personal data and will be securely deleted after verification.'
  },

  DRIVING_LICENCE: {
    id: 'driving_licence',
    name: 'Driving Licence',
    description: 'Valid UK driving licence for identity verification (sole traders only)',
    allowAlembaSync: false, // CRITICAL: NEVER sync to Alemba
    isSensitive: true,
    required: false, // Required for sole traders as ID
    section: 3,
    autoDeleteOnCompletion: true,
    retentionPeriod: '30 days after completion',
    acceptedFormats: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 5,
    warningMessage: 'This document contains sensitive personal data and will be securely deleted after verification.'
  },

  // Contract Stage Documents
  CONTRACT_AGREEMENT: {
    id: 'contract_agreement',
    name: 'Signed Contract/Agreement',
    description: 'Signed contract or service agreement',
    allowAlembaSync: true,
    isSensitive: false,
    required: false, // Required for OPW cases
    section: 'contract',
    conditionalRequired: {
      stage: 'contract'
    },
    acceptedFormats: ['.pdf'],
    maxSizeMB: 20
  },

  // System Generated Documents
  PBP_CERTIFICATE: {
    id: 'pbp_certificate',
    name: 'PBP Approval Certificate',
    description: 'System-generated PBP approval certificate',
    allowAlembaSync: true,
    isSensitive: false,
    required: false, // Generated by system
    section: 'pbp',
    systemGenerated: true,
    acceptedFormats: ['.pdf'],
    maxSizeMB: 2
  },

  COMPLETE_PDF: {
    id: 'complete_pdf',
    name: 'Complete Supplier Form PDF',
    description: 'Full supplier setup form PDF generated at completion',
    allowAlembaSync: true,
    isSensitive: false,
    required: false, // Generated at completion
    section: 'final',
    systemGenerated: true,
    acceptedFormats: ['.pdf'],
    maxSizeMB: 20
  },

  // Additional Supporting Documents
  INSURANCE_CERTIFICATE: {
    id: 'insurance_certificate',
    name: 'Insurance Certificate',
    description: 'Professional indemnity or public liability insurance certificate',
    allowAlembaSync: true,
    isSensitive: false,
    required: false,
    section: 6,
    acceptedFormats: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 10
  },

  VAT_CERTIFICATE: {
    id: 'vat_certificate',
    name: 'VAT Registration Certificate',
    description: 'HMRC VAT registration certificate',
    allowAlembaSync: true,
    isSensitive: false,
    required: false,
    section: 6,
    conditionalRequired: {
      field: 'vatRegistered',
      value: 'yes'
    },
    acceptedFormats: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 5
  },

  OTHER_SUPPORTING: {
    id: 'other_supporting',
    name: 'Other Supporting Document',
    description: 'Additional supporting documentation',
    allowAlembaSync: true, // Review individually
    isSensitive: false,
    required: false,
    section: 'other',
    acceptedFormats: ['.pdf', '.doc', '.docx', '.png', '.jpg', '.jpeg'],
    maxSizeMB: 10
  }
};

// Documents that are NEVER allowed to sync to Alemba
export const ALEMBA_FORBIDDEN_DOCS = [
  'passport',
  'driving_licence',
  'identity_document',
  'national_insurance', // If ever added
  'bank_statement'       // If ever added
];

// Documents that are allowed to sync to Alemba
export const ALEMBA_ALLOWED_DOCS = [
  'pbp_certificate',
  'letterhead_bank_details',
  'cest_form',
  'contract_agreement',
  'complete_pdf',
  'procurement_approval',
  'insurance_certificate',
  'vat_certificate'
];

/**
 * Check if a document type can be synced to Alemba
 * @param {string} documentType - The document type ID
 * @returns {boolean} - Whether the document can be synced
 */
export const canSyncToAlemba = (documentType) => {
  // First check forbidden list (highest priority)
  if (ALEMBA_FORBIDDEN_DOCS.includes(documentType?.toLowerCase())) {
    return false;
  }

  // Then check the document config
  const docConfig = Object.values(DOCUMENT_TYPES).find(
    d => d.id === documentType || d.id === documentType?.toLowerCase()
  );

  return docConfig?.allowAlembaSync === true;
};

/**
 * Check if a document type is sensitive
 * @param {string} documentType - The document type ID
 * @returns {boolean} - Whether the document is sensitive
 */
export const isSensitiveDocument = (documentType) => {
  const docConfig = Object.values(DOCUMENT_TYPES).find(
    d => d.id === documentType || d.id === documentType?.toLowerCase()
  );
  return docConfig?.isSensitive === true;
};

/**
 * Get the SharePoint library for a document type
 * @param {string} documentType - The document type ID
 * @returns {string} - The SharePoint library name
 */
export const getSharePointLibrary = (documentType) => {
  return isSensitiveDocument(documentType) ? 'SensitiveDocuments' : 'SupplierDocuments';
};

/**
 * Check if a document should be auto-deleted after completion
 * @param {string} documentType - The document type ID
 * @returns {boolean} - Whether the document should be auto-deleted
 */
export const shouldAutoDelete = (documentType) => {
  const docConfig = Object.values(DOCUMENT_TYPES).find(
    d => d.id === documentType || d.id === documentType?.toLowerCase()
  );
  return docConfig?.autoDeleteOnCompletion === true;
};

/**
 * Get document type configuration by ID
 * @param {string} documentType - The document type ID
 * @returns {Object|null} - The document configuration or null
 */
export const getDocumentConfig = (documentType) => {
  return Object.values(DOCUMENT_TYPES).find(
    d => d.id === documentType || d.id === documentType?.toLowerCase()
  ) || null;
};

/**
 * Get all documents required for a specific section
 * @param {number|string} section - The section number or identifier
 * @returns {Array} - Array of document configurations
 */
export const getDocumentsForSection = (section) => {
  return Object.values(DOCUMENT_TYPES).filter(d => d.section === section);
};

/**
 * Get all sensitive documents that need special handling
 * @returns {Array} - Array of sensitive document configurations
 */
export const getSensitiveDocuments = () => {
  return Object.values(DOCUMENT_TYPES).filter(d => d.isSensitive === true);
};

export default DOCUMENT_TYPES;
